src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RoomRepository::class)
 */
class Room
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $capacity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvailable = true;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, mappedBy="rooms")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        /*$time = date_format($this->created_at, "d-m-Y");
        new \DateTime::createFromImmutable($this->created_at);
        $this->created_at = $time;*/
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addRoom($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeRoom($this);
        }

        return $this;
    }

    /**
     * @param ArrayCollection $categories
     */
    public function setCategories(ArrayCollection $categories): void
    {
        $this->categories = $categories;
    }

    public function goodFormatTime($time): string
    {
        return date_format($time, "d-m-Y");;
    }

}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Room;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,

                'attr'=>[
                    'class'=>'input'
                ]
            ])
            ->add('capacity', IntegerType::class)
            ->add('city', TextType::class)
            ->add('description', TextareaType::class, [
                'constraints'=> [
                    new NotBlank([
                        'message'=>"Merci d'ajouter une description"
                    ]),
                    new Length([
                        'min'=>10,
                        'max'=>600,
                        'minMessage'=>'Message qui s\'affiche si le min n\'est pas atteint',
                        'maxMessage'=>'Message qui s\'affiche si le max est atteint',
                    ])
                ]
            ])
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
            'translation_domain'=>'room_form'
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Form\RoomType;
use App\Repository\RoomRepository;
use App\Entity\Room;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class RoomController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/room", name="room")
     */
    public function index(RoomRepository $roomRepository): Response
    {
        $totalRooms = $roomRepository->findAll();
        $rooms = $roomRepository->findBy(['isAvailable' => 'true']);
        $count = count($rooms);
        $total = count($totalRooms);
        return $this->render('room/index.html.twig', [
            'controller_name' => 'RoomController',
            'rooms' =>$rooms,
            'count' =>$count,
            'total' =>$total
        ]);
    }

    /**
     * @Route("/new", name="room.add", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     * @return Response
     *
     */
    public function new(Request $request) : Response
    {
        $room = new Room();
        $room->setUser($this->security->getUser());
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $room->setCreatedAt(new \DateTimeImmutable('now'));
            $room->setUpdatedAt(new \DateTimeImmutable('now'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            $this->addFlash('success', 'La salle a bien été ajoutée.');
            return $this->redirectToRoute('room');
        }

        return $this->render('room/new.html.twig', [
            'room'=>$room,
            'roomForm'=>$form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="room.edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     * @return Response
     *
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $room->setUpdatedAt(new \DateTimeImmutable('now'));
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Les modifications ont bien été pris en compte.');
           return $this->redirectToRoute('room');
        }


        return $this->render('room/edit.html.twig', [
            'room'=>$room,
            'roomForm'=>$form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="room.delete", methods={"DELETE"})
     * @IsGranted("ROLE_USER")
     * @return Response
     *
     */
    public function delete(Request $request, Room $room):Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();

            $this->addFlash('success', 'La salle a bien été supprimée.');
        }
        return $this->redirectToRoute('room');
    }
}

templates/room/_form.html.twig
{{ form_start(roomForm) }}
                {{ form_row(roomForm.name) }}
                {{ form_row(roomForm.capacity) }}
                {{ form_row(roomForm.city) }}
            {{ form_row(roomForm.description) }}
            {{ form_row(roomForm.categories) }}

<button type="submit" class="btn btn-primary mt-4">Valider</button>
{{ form_end(roomForm) }}

templates/room/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="card p-5 mt-5 w-50 shadow mx-auto">
        <h3 class="text-center">Modification de : </h3>
        {{ include('room/_form.html.twig') }}

    </div>
{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %} {% block body %}
<div class="container">
  {% for message in app.flashes('success') %}
    <div class="alert alert-success">
      {{ message }}
    </div>
  {% endfor %}
  {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <a type="button" class="btn btn-primary" href="{{ path('room.add') }}">Ajouter une salle</a>
  {% endif %}

  <h1>Salles disponibles ({{count}}/{{total}})</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">City</th>
        <th scope="col">Description</th>
        <th scope="col">Date de création</th>
        <th scope="col">Date de modification</th>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
          <th scope="col">Actions</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for room in rooms %}
      <tr>
        <td>{{ room.id }}</td>
        <td>{{ room.name }}</td>
        <td>{{ room.city }}</td>
        <td>{{ room.description | length > 60 ? room.description | slice(0,60) ~ '...' : room.description}}</td>
        <td>{{ room.goodFormatTime(room.createdAt) }}</td>
        <td>{{ room.goodFormatTime(room.updatedAt) }}</td>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <td>
          <a href="{{ path('room.edit', {id:room.id}) }}" type="button" class="btn btn-warning">Edit</a>
          <form method="post" action="{{ path('room.delete', {id:room.id}) }}" style="display:inline-block" onsubmit="return confirm('Confirmer la suppression ?')">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete'~room.id) }}">
            <button class="btn btn-danger">Delete</button>
          </form>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="card p-5 mt-5 w-50 shadow mx-auto">
        <h3 class="text-center">Ajouter une salle</h3>
        {{ include('room/_form.html.twig') }}

    </div>
{% endblock %}